### ISSUE TITLE
Wrong R Version in rstudio/r-base:4.1.3-focal DockerHub Image

### ISSUE THREAD

**Issue by FloLimebit** [rstudio/r-docker#86] opened 2022-09-13 11:16 UTC
The `r-base:4.1.3-focal` Image contains the R Version 3.6.3 instead of 4.1.3 in the latest digest: 

https://hub.docker.com/layers/rstudio/r-base/4.1.3-focal/images/sha256-3c391006becf4f9639454a729e1600344f353dd685981e528601457826d10194?context=explore

**Comment by ryanbthomas** [comment] 2022-09-13 13:42
Also r-base:3.6.3-bionic image contains R version 3.4.4

https://hub.docker.com/layers/rstudio/r-base/3.6.3-bionic/images/sha256-ab000df4487d5e1ec7cb843324b8ec8476bbab8db0bb701a358ea8d3dd92ecd5?context=explore

**Comment by glin** [comment] 2022-09-13 16:58
Thanks for the report, this is now fixed with a manual rerun of the job that builds these x.y.z patch version images. I'm now investigating what went wrong and how to prevent this from happening again. It's possibly related to some changes in the CI jobs I'm testing and/or an existing bug in the build scripts. Sorry about that.

**Closed by glin** 2022-09-13 16:58 UTC

**Comment by glin** [comment] 2022-09-14 21:32
This was hard to track down, but it was apparently caused by a pretty nasty bug with Docker using the wrong Dockerfile for caching in certain cases. #87 has more details on that, with a workaround for the Docker bug and tests to prevent wrong images from being published again.
